window.addEventListener("DOMContentLoaded", () => {
  const username = "mattpito";

  const pinnedRepos = [
    {
      name: "NatureMetabolism2025_GBM_MetPhenotypes",
      url: "https://github.com/mattpito/NatureMetabolism2025_GBM_MetPhenotypes",
      description: "Code for Nature Metabolism paper: Cell-intrinsic metabolic phenotypes identified in glioblastoma patients."
    },
    {
      name: "dragen-json-parcer",
      url: "https://github.com/mattpito/dragen-json-parcer",
      description: "Parse various information from annotated JSON files generated by DRAGEN pipeline."
    },
    {
      name: "nf__bam2RNAseq",
      url: "https://github.com/mattpito/nf__bam2RNAseq",
      description: "Nextflow workflow starting from BAM files, reverse engineering to FASTQ files."
    },
    {
      name: "3D_Omic_Integration",
      url: "https://github.com/mattpito/3D_Omic_Integration",
      description: "Aggregate sample modalities in 3D-ring structure for clinical intepretation of variants."
    },
    {
      name: "Nodular_Melanoma_Analysis",
      url: "https://github.com/mattpito/Nodular_Melanoma_Analysis",
      description: "Code for analysing Nodular Melanoma from NGS data."
    }
  ];


  const manualRepos = [
    {
      name: "MairLab_ClinicalDB_Lightsail",
      url: "https://github.com/manthosp/MairLab_ClinicalDB_Lightsail",
      description: "Clinical database/dashboard for multimodal GBM exploration using Django backend and React frontend."
    },
    {
      name: "PTBT",
      url: "https://github.com/manthosp/PTBT",
      description: "Analysis (Genomic Landscape) for Precision Brain Tumour Programme (work pending)."
    }
  ];

  const list = document.getElementById("repo-list");

  fetch(`https://api.github.com/users/${username}/repos?per_page=100`)
    .then(res => res.json())
    .then(repos => {
      const shown = new Set();

      // 📌 Pinned section
      const pinnedHeader = document.createElement("h3");
      pinnedHeader.textContent = "📌 Pinned Repositories";
      list.appendChild(pinnedHeader);

      pinnedRepos.forEach(repo => {
        const li = document.createElement("li");
        li.innerHTML = `
          <a href="${repo.url}" target="_blank">${repo.name}</a>
          <span> — ${repo.description}</span>
        `;
        list.appendChild(li);
        shown.add(repo.name);
      });

      // 🔹 Public section
      const publicHeader = document.createElement("h3");
      publicHeader.textContent = "🔹 Public Repositories";
      list.appendChild(publicHeader);

      repos.forEach(repo => {
        if (!shown.has(repo.name)) {
          const li = document.createElement("li");
          li.innerHTML = `
            <a href="${repo.html_url}" target="_blank">${repo.name}</a>
            <span> — ${repo.description || "No description"}</span>
          `;
          list.appendChild(li);
          shown.add(repo.name);
        }
      });

      // 🔒 Manual section
      const manualHeader = document.createElement("h3");
      manualHeader.style.marginTop = "2rem";
      manualHeader.textContent = "🔒 Not Public";
      list.appendChild(manualHeader);

      manualRepos.forEach(repo => {
        if (!shown.has(repo.name)) {
          const li = document.createElement("li");
          li.innerHTML = `
            <a href="${repo.url}" target="_blank">${repo.name}</a>
            <span> — ${repo.description}</span>
          `;
          list.appendChild(li);
        }
      });
    })
    .catch(err => {
      console.error("GitHub API error:", err);
      const fallback = document.createElement("li");
      fallback.textContent = "Unable to load repositories.";
      list.appendChild(fallback);
    });
});
